Vagrant.configure("2") do |slim|
  slim.vm.box = "minimal/centos7"
  slim.vm.hostname = "Kiosk"
  slim.vm.synced_folder '.', '/vagrant', disabled: true
  slim.vm.define "Kiosk"
  slim.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.gui = true
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "Kiosk"
  end

  slim.omnibus.chef_version = '14.12.9'
  slim.vm.provision "chef_apply" do |chef|
    chef.recipe = File.read("kiosk.rb")
  end
end
